#------------------- CONSTANTS  -----------------------------------------
BS_THRESHOLD                = 2.5       # Threshold value for bubble sensor 1
BUBBLE_DETECTION_PUMP_SPEED = 50        # speed of pump during bubble detection
DEFAULT_PUMP_SPEEED         = 1000      # speed of pump at start up
GANTRY_VER_SPEED            = 15.0      # vertical gantry speed
GANTRY_HOR_SPEED            = 15.0      # horizontal gantry speed
GANTRY_VER_ACCELERATION     = 1         # vertical gantry acceleration
GANTRY_HOR_ACCELERATION     = 1         # horizontal gantry acceleration
MIXING_ACCELERATION         = 1         # mixing motor acceleration
RPM_2_TML_SPEED             = 0.1365    # conversion from rpm to mixing motor TML unit  (0.267 for Reza's mixer)
TML_LENGTH_2_MM_VER         = 10. /1000      # tml unit for length to um
TML_LENGTH_2_MM_HOR         = 7.5 /1000      # tml unit for length to um
# pumps/valves RS485 addresses
TIRRANT_PUMP_ADDRESS        = 1         # Pump 1
TITRANT_LOOP_ADDRESS        = 2         # pump 1 loop valve
TITRANT_PIPETTE_ADDRESS     = 4         # titrant line: pipette valve
TITRANT_CLEANING_ADDRESS    = 3         # titrant line: cleaning valve
SAMPLE_PUMP_ADDRESS         = 5         # pump 2
SAMPLE_LOOP_ADDRESS         = 6         # pump 2 loop valve
TITRANT_PORT_ADDRESS        = 7         # sample line: titrant port valve
DEGASSER_ADDRESS            = 8         # sample line: degasser valve
SAMPLE_CLEANING_ADDRESS     = 9         # sample line: cleaning valve

pump1 = None
motors = None
labjack = None
tec = None

TEC_PORT = 0
TECHNOSOFT_PORT  = 0
PUMP1_PORT = 0
MIXER_AXIS_ID = 0
GANTRY_VER_AXIS_ID = 0
GANTRY_HOR_AXIS_ID = 0
MIXER_AXIS_ID = 0

pump1_titrant_active_led = False
pump1_titrant_homed_led = False
pump2_sample_active_led = False
pump2_sample_homed_led = False
horizontal_gantry_active_led = False
horizontal_gantry_homed_led = False
vertical_gantry_active_led = False
vertical_gantry_homed_led = False
mixing_motor_active_led = False
mixing_motor_homed_led = False
BS1 = 0
BS2 = 0
BS3 = 0
BS4 = 0
BS5 = 0
BS6 = 0
BS7 = 0
BS8 = 0
BS9 = 0
BS10 = 0
BS11 = 0
BS12 = 0
BS13 = 0
BS14 = 0
BS1_LED = False
BS2_LED = False
BS3_LED = False
BS4_LED = False
BS5_LED = False
BS6_LED = False
BS7_LED = False
BS8_LED = False
BS9_LED = False
BS10_LED = False
BS11_LED = False
BS12_LED = False
BS13_LED = False
BS14_LED = False
BS_THRESHOLD = 2.5
